[package]
name = "cif"
version = "0.1.0"
edition = "2024"
authors = ["Tobias <sandalbanditten@tutanota.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/sandalbanditten/cif"
description = """
A character builder for the Cosmere TTRPG.
"""


[dependencies]
